Public Module VA02ID
    Public Const PRESS_OK_ON_RDD_CHANGE_FIELD_BTN_ID As String = "wnd[1]/tbar[0]/btn[7]"
    Public Const PRESS_OPEN_NOTES_BTN_ID As String = "wnd[0]/mbar/menu[2]/menu[1]/menu[10]"
    Public Const CHANGE_RDD_TEXT_FIELD As String = "wnd[1]/usr/ctxtRV45A-S_ETDAT"
    Public Const CHANGE_RDD_BTN_ID As String = "wnd[0]/mbar/menu[1]/menu[1]/menu[3]"

    Public DEL_BLOCK_ID As String() = {
        "wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\01/ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/cmbVBAK-LIFSK",
        "wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\01/ssubSUBSCREEN_BODY:SAPMV45A:4402/ssubHEADER_FRAME:SAPMV45A:4440/cmbVBAK-LIFSK"
    }

    Public RDD_FIELD_ID As String() = {
        "wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\01/ssubSUBSCREEN_BODY:SAPMV45A:4402/ssubHEADER_FRAME:SAPMV45A:4440/ctxtRV45A-KETDAT",
        "wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\01/ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/ctxtRV45A-KETDAT"
    }
    Public Const CSR_FIELD_ID As String = "wnd[0]/usr/tabsTAXI_TABSTRIP_HEAD/tabpT\09/ssubSUBSCREEN_BODY:SAPMV45A:4152/subSUBSCREEN_TEXT:SAPLV70T:2100/cntlSPLITTER_CONTAINER/shellcont/shellcont/shell/shellcont[1]/shell"
    Public SELECT_ALL_BTN_ID As String() = {
        "wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\01/ssubSUBSCREEN_BODY:SAPMV45A:4400/subSUBSCREEN_TC:SAPMV45A:4900/subSUBSCREEN_BUTTONS:SAPMV45A:4050/btnBT_MKAL",
        "wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\01/ssubSUBSCREEN_BODY:SAPMV45A:4402/subSUBSCREEN_TC:SAPMV45A:4900/subSUBSCREEN_BUTTONS:SAPMV45A:4050/btnBT_MKAL"
    }
    Public Const ORDER_NUNBER_INPUT_TEXT_FIELD_ID As String = "wnd[0]/usr/ctxtVBAK-VBELN"
    Public Const SECOND_POPUP_WINDOW_ID As String = "wnd[2]/usr/txtMESSTXT1"
    Public Const INCOMPLETE_DOCUMENT_POPUP_ID As String = "wnd[1]/usr/txtSPOP-TEXTLINE1"
    Public Const INCOMPLETE_DOCUMENT_YES_BTN_ID As String = "wnd[1]/usr/btnSPOP-VAROPTION1"
    Public FIRST_ROW_OF_SALES_TAB_TABLE_ID As String() = {
        "wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\01/ssubSUBSCREEN_BODY:SAPMV45A:4402/subSUBSCREEN_TC:SAPMV45A:4900/tblSAPMV45ATCTRL_U_ERF_AUFTRAG",
        "wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\01/ssubSUBSCREEN_BODY:SAPMV45A:4402/subSUBSCREEN_TC:SAPMV45A:4900/tblSAPMV45ATCTRL_U_ERF_AUFTRAG"
    }
    Public Const SHIPPING_TAB_ID As String = "wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\06"
    Public Const SHIPPING_TAB_TABLE_ID As String = "wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\06/ssubSUBSCREEN_BODY:SAPMV45A:4403/subSUBSCREEN_TC:SAPMV45A:4921/tblSAPMV45ATCTRL_UEIN_VERSAND"

    Public Const REJECTIONS_TAB_ID As String = "wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\07"
End Module
